apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: otel-demo
spec:
  exporter:
    endpoint: http://my-opentelemetry-collector.opentelemetry.svc.cluster.local:4318

  sampler:
    type: parentbased_always_on

  propagators:
    - tracecontext
    - baggage
    - b3

  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
        
      - name: OTEL_EXPORTER_OTLP_INSECURE
        value: "true"
        
      - name: OTEL_EXPORTER_OTLP_TIMEOUT
        value: "30000"
        
      - name: OTEL_LOG_LEVEL
        value: info
        
